name: Install and Run Dad Jokes
run-name: ${{ github.run_id }}

on: ['push']
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Install dad-jokes package globally
        run: npm install --global @mikemcbride/dad-jokes

      - name: Run dad-jokes and capture output
        run: |
          dad-jokes > dad_jokes_output.txt

      - name: Commit and push results to a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b new
          git add dad_jokes_output.txt
          git commit -m "Add dad jokes output"
          git push origin new
